# Directori on es guardaran tots els fitxers
es.caib.enviafib.filesdirectory=D:/Projectes/enviafib-files

# Url per enviament de peticions de firma a PortaFIB
#es.caib.enviafib.portafib.apifirmaasync.url=https://governdigital.fundaciobit.org/portafib3/common/rest/apifirmaasyncsimple/v2/
es.caib.enviafib.portafib.apifirmaasync.url=https://governdigital.fundaciobit.org/portafib/common/rest/apifirmaasyncsimple/v2/
#es.caib.enviafib.portafib.apifirmaasync.url=https://portafibdev.fundaciobit.org/portafib/common/rest/apifirmaasyncsimple/v2/
#es.caib.enviafib.portafib.apifirmaasync.url=http://192.168.39.17:8080/portafib/common/rest/apifirmaasyncsimple/v2/
es.caib.enviafib.portafib.apifirmaasync.username=username
es.caib.enviafib.portafib.apifirmaasync.password=password
es.caib.enviafib.portafib.apifirmaasync.profile.pades=ENVIAFIB_PADES


# Url per les firmes Síncrones PortaFIB 
#es.caib.enviafib.portafib.apifirmaweb.url=https://governdigital.fundaciobit.org/portafib3/common/rest/apifirmawebsimple/v1/
es.caib.enviafib.portafib.apifirmaweb.url=https://governdigital.fundaciobit.org/portafib/common/rest/apifirmawebsimple/v1/
#es.caib.enviafib.portafib.apifirmaweb.url=https://portafibdev.fundaciobit.org/portafib/common/rest/apifirmawebsimple/v1/
#es.caib.enviafib.portafib.apifirmaweb.url=http://192.168.39.17:8080/portafib/common/rest/apifirmawebsimple/v1/
es.caib.enviafib.portafib.apifirmaweb.username=username
es.caib.enviafib.portafib.apifirmaweb.password=password

# Url a API de Flux de Firmes de PortaFIB
#es.caib.enviafib.portafib.apiflow.url=https://governdigital.fundaciobit.org/portafib3/common/rest/apiflowtemplatesimple/v1/
es.caib.enviafib.portafib.apiflow.url=https://governdigital.fundaciobit.org/portafib/common/rest/apiflowtemplatesimple/v1/
#es.caib.enviafib.portafib.apiflow.url=https://portafibdev.fundaciobit.org/portafib/common/rest/apiflowtemplatesimple/v1/
#es.caib.enviafib.portafib.apiflow.url=http://192.168.39.17:8080/portafib/common/rest/apiflowtemplatesimple/v1/
es.caib.enviafib.portafib.apiflow.username=username
es.caib.enviafib.portafib.apiflow.password=password

# URL a API de Revisors de PortaFIB
es.caib.enviafib.portafib.apirevisors.host=https://governdigital.fundaciobit.org/portafibapi/interna
es.caib.enviafib.portafib.apirevisors.username=username
es.caib.enviafib.portafib.apirevisors.password=password


# PLUGIN ESTRUCTURA ORGANITZATIVA - LDAP CAIB
es.caib.enviafib.pluginsib.estructuraorganitzativa.ldapcaib.ldap.host_url=ldap\://sdesauthlin1.caib.es\:389
es.caib.enviafib.pluginsib.estructuraorganitzativa.ldapcaib.dir3host=https://se.caib.es/dir3caib/rest
es.caib.enviafib.pluginsib.estructuraorganitzativa.ldapcaib.ldap.security_principal=username
es.caib.enviafib.pluginsib.estructuraorganitzativa.ldapcaib.ldap.security_credentials=fib$password



# PLUGIN ARXIU - CAIB
es.caib.enviafib.pluginsib.arxiu.caib.base.url=https://esbse.caib.es:4430/esb
es.caib.enviafib.pluginsib.arxiu.caib.aplicacio.codi=ENVIAFIB
es.caib.enviafib.pluginsib.arxiu.caib.usuari=username
es.caib.enviafib.pluginsib.arxiu.caib.contrasenya=password

es.caib.enviafib.pluginsib.arxiu.caib.conversio.imprimible.url=https://se.caib.es/concsvapi/interna/printable/uuid
es.caib.enviafib.pluginsib.arxiu.caib.conversio.imprimible.usuari=username
es.caib.enviafib.pluginsib.arxiu.caib.conversio.imprimible.contrasenya=password


# EXECUCIÓ DEL SCHEDULER PER TANCAR EXPEDIENTS
es.caib.enviafib.arxiu.tancarexpedient.scheduler.hora=12
es.caib.enviafib.arxiu.tancarexpedient.scheduler.nhores=1
es.caib.enviafib.arxiu.tancarexpedient.scheduler.maxreintents=4

# EXECUCIÓ DEL SCHEDULER PER REINTENTAR ARXIVAT
es.caib.enviafib.arxiu.reintentarxivat.scheduler.hora=10
es.caib.enviafib.arxiu.reintentarxivat.scheduler.nhores=1
es.caib.enviafib.arxiu.reintentarxivat.scheduler.maxreintents=4



#  ======== PLUGIN USER-INFORMATION - KEYCLOAK =======

es.caib.enviafib.userinformationplugin=org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin
es.caib.enviafib.pluginsib.userinformation.keycloak.serverurl=http://192.168.35.165:18080/auth/
#https://otae.fundaciobit.org/auth/
es.caib.enviafib.pluginsib.userinformation.keycloak.realm=GOIB
es.caib.enviafib.pluginsib.userinformation.keycloak.client_id=goib-ws
es.caib.enviafib.pluginsib.userinformation.keycloak.password_secret=password
es.caib.enviafib.pluginsib.userinformation.keycloak.client_id_for_user_autentication=goib-default

# Mappings. Mapejos entre valors de Attibutes de un usuari i els valors de UserInfo de PluginUserInformation
# Clau:  username, administrationID, name, surname1, surname2, email, language,
#        phoneNumber, password,  address, company, website o gender( -1: unknown or undefined, 0 female, 1 male)
# Valor:  Atribut definit dins "Attributes" de l'usuari Keycloak
es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.administrationID=nif

#es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.companyDepartment=departmentNumber
#es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.companyArea=areaNumber

es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.dir3=dir3
es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.dir3Parent=dir3pare

# Només en entorns CAIB. S'utilitzen els valors de DIR3 i DIR3PARENT per 
# assignar valors a Area (companyArea) i Departament (companyDepartment)
# IMPORTANT: Si aquesta propietat està definida i dir3 o dir3Parent valen null llavors llançarà un error 
# IMPORTANT: Si aquesta propietat està definida i companyArea o companyDepartment valen diferent de null
# llavors llançarà un error
# El valor d'aquesta propietat ha de ser el DIR3 arrel de l'organització
#es.caib.enviafib.pluginsib.userinformation.keycloak.useDir3InfoToGenerateAreaDepartment=A04003003

#es.caib.enviafib.pluginsib.userinformation.keycloak.mapping.surname1=sn1
#es.caib.enviafib..pluginsib.userinformation.keycloak.mapping.surname2=sn2
# Per depuració
es.caib.enviafib.pluginsib.userinformation.keycloak.debug=true


#  ======== PLUGIN USER-INFORMATION - DATABASE ======= -->
#es.caib.enviafib.userinformationplugin=org.fundaciobit.plugins.userinformation.database.DataBaseUserInformationPlugin
es.caib.enviafib.pluginsib.userinformation.database.jndi=java:jboss/datasources/seyconDS
es.caib.enviafib.pluginsib.userinformation.database.users_table=SC_WL_USUARI
es.caib.enviafib.pluginsib.userinformation.database.username_column=USU_CODI
es.caib.enviafib.pluginsib.userinformation.database.administrationid_column=USU_NIF
es.caib.enviafib.pluginsib.userinformation.database.name_column=USU_NOM
#es.caib.enviafib.pluginsib.userinformation.database.surname_1_column
#es.caib.enviafib.pluginsib.userinformation.database.surname_2_column      
#es.caib.enviafib.pluginsib.userinformation.database.language_column
#es.caib.enviafib.pluginsib.userinformation.database.telephone_column
#es.caib.enviafib.pluginsib.userinformation.database.email_column=CONCAT(USU_CODI,'@fundaciobit.org')
#es.caib.enviafib.pluginsib.userinformation.database.gender_column
#es.caib.enviafib.pluginsib.userinformation.database.password_column
es.caib.enviafib.pluginsib.userinformation.database.userroles_table=SC_WL_USUGRU
es.caib.enviafib.pluginsib.userinformation.database.userroles_rolename_column=UGR_CODGRU
es.caib.enviafib.pluginsib.userinformation.database.userroles_username_column=UGR_CODUSU


#  ======== PLUGIN USER-INFORMATION - LDAP ======= 

# es.caib.enviafib.userinformationplugin=org.fundaciobit.plugins.userinformation.ldap.LdapUserInformationPlugin
# es.caib.enviafib.pluginsib.userinformation.ldap.host_url=ldap://ldap.ibit.org:389
# es.caib.enviafib.pluginsib.userinformation.ldap.security_principal=[LDAPUSERNAME]
# es.caib.enviafib.pluginsib.userinformation.ldap.security_authentication=simple
# es.caib.enviafib.pluginsib.userinformation.ldap.security_credentials=[PASSWORD of LDAPUSERNAME]
# es.caib.enviafib.pluginsib.userinformation.ldap.users_context_dn=cn=Users,dc=ibitnet,dc=lan
# es.caib.enviafib.pluginsib.userinformation.ldap.search_scope=onelevel
# es.caib.enviafib.pluginsib.userinformation.ldap.search_filter=(|(memberOf=CN=@PFI_ADMIN,CN=Users,DC=ibitnet,DC=lan)(memberOf=CN=@PFI_USER,CN=Users,DC=ibitnet,DC=lan))
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.username=sAMAccountName
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.mail=mail
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.administration_id=postOfficeBox
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.name=givenName
# Has de triar:
#       - "surname1" i "surname2"
#       - "surname"
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.surname=sn

# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.surname1=sn1
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.surname2=sn2

# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.telephone=telephoneNumber
# es.caib.enviafib.pluginsib.userinformation.ldap.attribute.memberof=memberOf
# es.caib.enviafib.pluginsib.userinformation.ldap.prefix_role_match_memberof=CN=@
# es.caib.enviafib.pluginsib.userinformation.ldap.suffix_role_match_memberof=,CN=Users,DC=ibitnet,DC=lan