

# Dialecte de Hibernate
es.caib.enviafib.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# es.caib.enviafib.hibernate.dialect=org.hibernate.dialect.MySQLDialect      
# es.caib.enviafib.hibernate.dialect=org.hibernate.dialect.DB2Dialect
# es.caib.enviafib.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# es.caib.enviafib.hibernate.dialect=net.sf.hibernate.dialect.Oracle9Dialect

# es.caib.enviafib.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
# es.caib.enviafib.hibernate.query.substitutions=true 1, false 0
es.caib.enviafib.hibernate.show_sql=false
es.caib.enviafib.hibernate.format_sql=false


# Propietat que indica als projectes que activin les caracteristiques
# especials requerides en l'entorn de la CAIB (Govern Balear) si val true -->
es.caib.enviafib.iscaib=false


#  Tipus de FileSystemManager
es.caib.enviafib.filesystemmanagerclass=org.fundaciobit.genapp.common.filesystem.SimpleFileSystemManager
#  Si volem distribuir els fitxers en directoris, llavors utilitzar aquesta classe.
#  Revisar punt "Migracio de 1.1.4 a 2.0.0 del 'Manual de Migracions'
#es.caib.enviafib.filesystemmanagerclass=org.fundaciobit.genapp.common.filesystem.ThreeFolderFileSystemManager

es.caib.enviafib.defaultlanguage=ca

es.caib.enviafib.development=false

#  Clau per encriptar l'identificador del fitxers a descarregar via web(IMPORTANT tamany de 16 caràcters) -->
es.caib.enviafib.encryptkey=1234567890123456

#  Llistat de Plugins per l'exportació de dades en els llistats (excel, ods, csv, ...) -->
# es.caib.enviafib.exportdataplugins=org.fundaciobit.plugins.exportdata.cvs.CSVPlugin,org.fundaciobit.plugins.exportdata.ods.ODSPlugin,org.fundaciobit.plugins.exportdata.excel.ExcelPlugin

#Camps que apareixen a l'ajuda
es.caib.enviafib.ajuda.telefon=971176060
es.caib.enviafib.ajuda.web=http://otae.fundaciobit.org
es.caib.enviafib.ajuda.email=otae@fundaciobit.org

# Adressa des de on s’envien els emails enviats per l’aplicacio EnviaFIB
es.caib.enviafib.email.from=noreply.enviafib@enviafib.org

# Url base de desplegament de Enviafib
es.caib.enviafib.url=http://ptrias:8080/enviafibback

es.caib.enviafib.email.from=otae@fundaciobit.org
es.caib.enviafib.url_sortida=

# Propietat que indica si volem les opcions de menú per gestionar la taula de bbdd
# que conté les dades de l'estructura organitzativa pel Plugin d'Estructura 
# Organitzativa de DATABASE.
es.caib.enviafib.showmenuestructuraorganitzativa=true

#   Afegir aqui altres propietats 
