/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.api;

import es.caib.enviafib.apiinterna.client.services.ApiException;
import es.caib.enviafib.apiinterna.client.model.PortaFIBEvent;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CallbackApi
 */
@Ignore
public class CallbackApiTest {

    private final CallbackApi api = new CallbackApi();

    /**
     * Reb l&#x27;event de portafib realitza les accions corresponents
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void event1Test() throws ApiException {
        PortaFIBEvent response = api.event1();

        // TODO: test validations
    }
}
