/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.api;

import es.caib.enviafib.apiinterna.client.services.ApiException;
import es.caib.enviafib.apiinterna.client.model.PeticioDeFirmaPaginacio;
import es.caib.enviafib.apiinterna.client.model.RestExceptionInfo;
import es.caib.enviafib.apiinterna.client.model.TipusDocumentalsAllElements;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DadesObertesEnviaFibApi
 */
public class DadesObertesEnviaFibApiTest {

    private final DadesObertesEnviaFibApi api = new DadesObertesEnviaFibApi();

    /**
     * Retorna un llistat amb la informacio de les peticions de firma
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void peticionsdefirmaTest() throws ApiException {
        //
        //String startdate = null;
        //
        //String enddate = null;
        //
        //Integer page = null;
        //
        //Integer pageSize = null;
        //
        //String language = null;
        //
        //PeticioDeFirmaPaginacio response = api.peticionsdefirma(startdate, enddate, page, pageSize, language);

        // TODO: test validations
    }
    /**
     * Retorna un llistat de tots els tipus documentals
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tipusdocumentalsTest() throws ApiException {
        //
        //String language = null;
        //
        //TipusDocumentalsAllElements response = api.tipusdocumentals(language);

        // TODO: test validations
    }
}
