/*
 * API REST INTERNA de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0
 * Contact: governdigital.enviafib@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.api;

import es.caib.enviafib.apiinterna.client.services.ApiClient;
import es.caib.enviafib.apiinterna.client.services.ApiException;
import es.caib.enviafib.apiinterna.client.model.PeticioDeFirmaPaginacio;
import es.caib.enviafib.apiinterna.client.model.TipusDocumentalsPaginacio;

import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DadesObertesEnviaFibApi
 */
@Ignore
public class DadesObertesEnviaFibApiTest {

    public static void main(String[] args) {
        try {
            //new DadesObertesEnviaFibApiTest().tipusdocumentalsTest();
            new DadesObertesEnviaFibApiTest().peticionsdefirmaTest();
            
            System.out.println("FINAL");
        } catch (ApiException e) {
            
            System.err.println(e.getCode());
            System.err.println(e.getLocalizedMessage());
            System.err.println(e.getMessage());
            System.err.println(e.getResponseBody());
            
            
            
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    protected DadesObertesEnviaFibApi getApi() {
        
        
        ApiClient apiclient = new ApiClient();
        
        apiclient.setBasePath("http://anadal:8888/enviafibapi/interna");
        
        apiclient.setUsername("enviafibapp");
        apiclient.setPassword("enviafibapp");
        
        apiclient.setDebugging(true);
        
        //apiclient.addDefaultHeader("content-type", "application/json");
        
        DadesObertesEnviaFibApi api = new DadesObertesEnviaFibApi(apiclient);
        
        return api;
    }
    

    /**
     * Retorna un llistat amb la informacio de totes les peticions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void peticionsdefirmaTest() throws ApiException {
        String inici = "11-08-2022";
        String fi = "11-12-2021";
        Integer page = 1;
        Integer pagesize = 10;
        String language = "es";
        DadesObertesEnviaFibApi api = getApi();
        PeticioDeFirmaPaginacio response = api.peticionsdefirma(inici, fi, page, pagesize, language);

        System.out.println(response);
    }
    /**
     * Retorna un llistat dels tipus documentals
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tipusdocumentalsTest() throws ApiException {
        String language = "ca";
        DadesObertesEnviaFibApi api = getApi();
        TipusDocumentalsPaginacio response = api.tipusdocumentals(language);

        System.out.println(response);
        // TODO: test validations
    }
}
