/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.api;

import es.caib.enviafib.apiinterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PeticionsApi
 */
@Ignore
public class PeticionsApiTest {

    private final PeticionsApi api = new PeticionsApi();

    /**
     * Retorna un llistat amb la informacio de totes les peticions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void obtenirDadesPeticionsTest() throws ApiException {
        String response = api.obtenirDadesPeticions();

        // TODO: test validations
    }
}
