-- create index efi_entitat_pk_i on efi_entitat (entitatid);
create index efi_entitat_logowebid_fk_i on efi_entitat (logowebid);
create index efi_entitat_logosegellid_fk_i on efi_entitat (logosegellid);
-- create index efi_faq_pk_i on efi_faq (faqid);
create index efi_faq_fitxer2id_fk_i on efi_faq (fitxer2id);
-- create index efi_fitxer_pk_i on efi_fitxer (fitxerid);
-- create index efi_grupusuari_pk_i on efi_grupusuari (grupusuariid);
create index efi_grupusuari_usuariid_fk_i on efi_grupusuari (usuariid);
-- create index efi_infoanex_pk_i on efi_infoanex (infoanexid);
create index efi_infoanex_anexid_fk_i on efi_infoanex (anexid);
-- create index efi_infosignatura_pk_i on efi_infosignatura (infosignaturaid);
create index efi_menu_titolmenuid_fk_i on efi_menu (titolmenuid);
create index efi_menu_grupid_fk_i on efi_menu (grupid);
-- create index efi_peticio_pk_i on efi_peticio (peticioid);
create index efi_peticio_solicitantid_fk_i on efi_peticio (solicitantid);
create index efi_peticio_fitxer_firma_fk_i on efi_peticio (fitxer_firmatid);
create index efi_peticio_infoarxiuid_fk_i on efi_peticio (infoarxiuid);
-- create index efi_seriedocumental_pk_i on efi_seriedocumental (seriedocumentalid);
-- create index efi_usuari_pk_i on efi_usuari (usuariid);
create index efi_usuari_entitatid_fk_i on efi_usuari (entitatid);
create index efi_usuarientitat_usuari_fk_i on efi_usuarientitat (usuariid);
