/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PeticioDeFirma
 */
public class PeticioDeFirmaTest {
    private final PeticioDeFirma model = new PeticioDeFirma();

    /**
     * Model tests for PeticioDeFirma
     */
    @Test
    public void testPeticioDeFirma() {
        // TODO: test PeticioDeFirma
    }

    /**
     * Test the property 'nif'
     */
    @Test
    public void nifTest() {
        // TODO: test nif
    }

    /**
     * Test the property 'titol'
     */
    @Test
    public void titolTest() {
        // TODO: test titol
    }

    /**
     * Test the property 'creada'
     */
    @Test
    public void creadaTest() {
        // TODO: test creada
    }

    /**
     * Test the property 'finalitzada'
     */
    @Test
    public void finalitzadaTest() {
        // TODO: test finalitzada
    }

    /**
     * Test the property 'idiomaCode'
     */
    @Test
    public void idiomaCodeTest() {
        // TODO: test idiomaCode
    }

    /**
     * Test the property 'idiomaDescription'
     */
    @Test
    public void idiomaDescriptionTest() {
        // TODO: test idiomaDescription
    }

    /**
     * Test the property 'tipusDocumentalCode'
     */
    @Test
    public void tipusDocumentalCodeTest() {
        // TODO: test tipusDocumentalCode
    }

    /**
     * Test the property 'tipusDocumentalDescription'
     */
    @Test
    public void tipusDocumentalDescriptionTest() {
        // TODO: test tipusDocumentalDescription
    }

    /**
     * Test the property 'tipusPeticioCode'
     */
    @Test
    public void tipusPeticioCodeTest() {
        // TODO: test tipusPeticioCode
    }

    /**
     * Test the property 'tipusPeticioDescription'
     */
    @Test
    public void tipusPeticioDescriptionTest() {
        // TODO: test tipusPeticioDescription
    }

    /**
     * Test the property 'dir3'
     */
    @Test
    public void dir3Test() {
        // TODO: test dir3
    }

}
