/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.enviafib.apiinterna.client.model.PeticioDeFirma;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PeticioDeFirmaPaginacio
 */
public class PeticioDeFirmaPaginacioTest {
    private final PeticioDeFirmaPaginacio model = new PeticioDeFirmaPaginacio();

    /**
     * Model tests for PeticioDeFirmaPaginacio
     */
    @Test
    public void testPeticioDeFirmaPaginacio() {
        // TODO: test PeticioDeFirmaPaginacio
    }

    /**
     * Test the property 'pagesize'
     */
    @Test
    public void pagesizeTest() {
        // TODO: test pagesize
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'totalpages'
     */
    @Test
    public void totalpagesTest() {
        // TODO: test totalpages
    }

    /**
     * Test the property 'totalcount'
     */
    @Test
    public void totalcountTest() {
        // TODO: test totalcount
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
