/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RestExceptionInfo
 */
public class RestExceptionInfoTest {
    private final RestExceptionInfo model = new RestExceptionInfo();

    /**
     * Model tests for RestExceptionInfo
     */
    @Test
    public void testRestExceptionInfo() {
        // TODO: test RestExceptionInfo
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'stackTrace'
     */
    @Test
    public void stackTraceTest() {
        // TODO: test stackTrace
    }

    /**
     * Test the property 'causeException'
     */
    @Test
    public void causeExceptionTest() {
        // TODO: test causeException
    }

    /**
     * Test the property 'causeStackTrace'
     */
    @Test
    public void causeStackTraceTest() {
        // TODO: test causeStackTrace
    }

}
