/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Elements retornats
 */
@JsonPropertyOrder({
  PeticioDeFirma.JSON_PROPERTY_NIF,
  PeticioDeFirma.JSON_PROPERTY_TITOL,
  PeticioDeFirma.JSON_PROPERTY_CREADA,
  PeticioDeFirma.JSON_PROPERTY_FINALITZADA,
  PeticioDeFirma.JSON_PROPERTY_IDIOMA_CODE,
  PeticioDeFirma.JSON_PROPERTY_IDIOMA_DESCRIPTION,
  PeticioDeFirma.JSON_PROPERTY_TIPUS_DOCUMENTAL_CODE,
  PeticioDeFirma.JSON_PROPERTY_TIPUS_DOCUMENTAL_DESCRIPTION,
  PeticioDeFirma.JSON_PROPERTY_TIPUS_PETICIO_CODE,
  PeticioDeFirma.JSON_PROPERTY_TIPUS_PETICIO_DESCRIPTION,
  PeticioDeFirma.JSON_PROPERTY_DIR3
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PeticioDeFirma {
  public static final String JSON_PROPERTY_NIF = "nif";
  private String nif;

  public static final String JSON_PROPERTY_TITOL = "titol";
  private String titol;

  public static final String JSON_PROPERTY_CREADA = "creada";
  private OffsetDateTime creada;

  public static final String JSON_PROPERTY_FINALITZADA = "finalitzada";
  private OffsetDateTime finalitzada;

  public static final String JSON_PROPERTY_IDIOMA_CODE = "idiomaCode";
  private String idiomaCode;

  public static final String JSON_PROPERTY_IDIOMA_DESCRIPTION = "idiomaDescription";
  private String idiomaDescription;

  public static final String JSON_PROPERTY_TIPUS_DOCUMENTAL_CODE = "tipusDocumentalCode";
  private String tipusDocumentalCode;

  public static final String JSON_PROPERTY_TIPUS_DOCUMENTAL_DESCRIPTION = "tipusDocumentalDescription";
  private String tipusDocumentalDescription;

  public static final String JSON_PROPERTY_TIPUS_PETICIO_CODE = "tipusPeticioCode";
  private Integer tipusPeticioCode;

  public static final String JSON_PROPERTY_TIPUS_PETICIO_DESCRIPTION = "tipusPeticioDescription";
  private String tipusPeticioDescription;

  public static final String JSON_PROPERTY_DIR3 = "dir3";
  private String dir3;

  public PeticioDeFirma() {
  }

  public PeticioDeFirma nif(String nif) {
    
    this.nif = nif;
    return this;
  }

   /**
   * Get nif
   * @return nif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNif(String nif) {
    this.nif = nif;
  }


  public PeticioDeFirma titol(String titol) {
    
    this.titol = titol;
    return this;
  }

   /**
   * Get titol
   * @return titol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitol() {
    return titol;
  }


  @JsonProperty(JSON_PROPERTY_TITOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitol(String titol) {
    this.titol = titol;
  }


  public PeticioDeFirma creada(OffsetDateTime creada) {
    
    this.creada = creada;
    return this;
  }

   /**
   * Get creada
   * @return creada
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREADA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreada() {
    return creada;
  }


  @JsonProperty(JSON_PROPERTY_CREADA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreada(OffsetDateTime creada) {
    this.creada = creada;
  }


  public PeticioDeFirma finalitzada(OffsetDateTime finalitzada) {
    
    this.finalitzada = finalitzada;
    return this;
  }

   /**
   * Get finalitzada
   * @return finalitzada
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINALITZADA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFinalitzada() {
    return finalitzada;
  }


  @JsonProperty(JSON_PROPERTY_FINALITZADA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinalitzada(OffsetDateTime finalitzada) {
    this.finalitzada = finalitzada;
  }


  public PeticioDeFirma idiomaCode(String idiomaCode) {
    
    this.idiomaCode = idiomaCode;
    return this;
  }

   /**
   * Get idiomaCode
   * @return idiomaCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDIOMA_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdiomaCode() {
    return idiomaCode;
  }


  @JsonProperty(JSON_PROPERTY_IDIOMA_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdiomaCode(String idiomaCode) {
    this.idiomaCode = idiomaCode;
  }


  public PeticioDeFirma idiomaDescription(String idiomaDescription) {
    
    this.idiomaDescription = idiomaDescription;
    return this;
  }

   /**
   * Get idiomaDescription
   * @return idiomaDescription
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDIOMA_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdiomaDescription() {
    return idiomaDescription;
  }


  @JsonProperty(JSON_PROPERTY_IDIOMA_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdiomaDescription(String idiomaDescription) {
    this.idiomaDescription = idiomaDescription;
  }


  public PeticioDeFirma tipusDocumentalCode(String tipusDocumentalCode) {
    
    this.tipusDocumentalCode = tipusDocumentalCode;
    return this;
  }

   /**
   * Get tipusDocumentalCode
   * @return tipusDocumentalCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTipusDocumentalCode() {
    return tipusDocumentalCode;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusDocumentalCode(String tipusDocumentalCode) {
    this.tipusDocumentalCode = tipusDocumentalCode;
  }


  public PeticioDeFirma tipusDocumentalDescription(String tipusDocumentalDescription) {
    
    this.tipusDocumentalDescription = tipusDocumentalDescription;
    return this;
  }

   /**
   * Get tipusDocumentalDescription
   * @return tipusDocumentalDescription
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTipusDocumentalDescription() {
    return tipusDocumentalDescription;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusDocumentalDescription(String tipusDocumentalDescription) {
    this.tipusDocumentalDescription = tipusDocumentalDescription;
  }


  public PeticioDeFirma tipusPeticioCode(Integer tipusPeticioCode) {
    
    this.tipusPeticioCode = tipusPeticioCode;
    return this;
  }

   /**
   * Get tipusPeticioCode
   * @return tipusPeticioCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_PETICIO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTipusPeticioCode() {
    return tipusPeticioCode;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_PETICIO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusPeticioCode(Integer tipusPeticioCode) {
    this.tipusPeticioCode = tipusPeticioCode;
  }


  public PeticioDeFirma tipusPeticioDescription(String tipusPeticioDescription) {
    
    this.tipusPeticioDescription = tipusPeticioDescription;
    return this;
  }

   /**
   * Get tipusPeticioDescription
   * @return tipusPeticioDescription
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_PETICIO_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTipusPeticioDescription() {
    return tipusPeticioDescription;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_PETICIO_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusPeticioDescription(String tipusPeticioDescription) {
    this.tipusPeticioDescription = tipusPeticioDescription;
  }


  public PeticioDeFirma dir3(String dir3) {
    
    this.dir3 = dir3;
    return this;
  }

   /**
   * Get dir3
   * @return dir3
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIR3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDir3() {
    return dir3;
  }


  @JsonProperty(JSON_PROPERTY_DIR3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDir3(String dir3) {
    this.dir3 = dir3;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeticioDeFirma peticioDeFirma = (PeticioDeFirma) o;
    return Objects.equals(this.nif, peticioDeFirma.nif) &&
        Objects.equals(this.titol, peticioDeFirma.titol) &&
        Objects.equals(this.creada, peticioDeFirma.creada) &&
        Objects.equals(this.finalitzada, peticioDeFirma.finalitzada) &&
        Objects.equals(this.idiomaCode, peticioDeFirma.idiomaCode) &&
        Objects.equals(this.idiomaDescription, peticioDeFirma.idiomaDescription) &&
        Objects.equals(this.tipusDocumentalCode, peticioDeFirma.tipusDocumentalCode) &&
        Objects.equals(this.tipusDocumentalDescription, peticioDeFirma.tipusDocumentalDescription) &&
        Objects.equals(this.tipusPeticioCode, peticioDeFirma.tipusPeticioCode) &&
        Objects.equals(this.tipusPeticioDescription, peticioDeFirma.tipusPeticioDescription) &&
        Objects.equals(this.dir3, peticioDeFirma.dir3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nif, titol, creada, finalitzada, idiomaCode, idiomaDescription, tipusDocumentalCode, tipusDocumentalDescription, tipusPeticioCode, tipusPeticioDescription, dir3);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeticioDeFirma {\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    titol: ").append(toIndentedString(titol)).append("\n");
    sb.append("    creada: ").append(toIndentedString(creada)).append("\n");
    sb.append("    finalitzada: ").append(toIndentedString(finalitzada)).append("\n");
    sb.append("    idiomaCode: ").append(toIndentedString(idiomaCode)).append("\n");
    sb.append("    idiomaDescription: ").append(toIndentedString(idiomaDescription)).append("\n");
    sb.append("    tipusDocumentalCode: ").append(toIndentedString(tipusDocumentalCode)).append("\n");
    sb.append("    tipusDocumentalDescription: ").append(toIndentedString(tipusDocumentalDescription)).append("\n");
    sb.append("    tipusPeticioCode: ").append(toIndentedString(tipusPeticioCode)).append("\n");
    sb.append("    tipusPeticioDescription: ").append(toIndentedString(tipusPeticioDescription)).append("\n");
    sb.append("    dir3: ").append(toIndentedString(dir3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

