/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Estructura de dades utilitzada per passar informació d&#x27;un error
 */
@Schema(description = "Estructura de dades utilitzada per passar informació d'un error")

public class RestExceptionInfo {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  @JsonProperty("stackTrace")
  private String stackTrace = null;

  @JsonProperty("causeException")
  private String causeException = null;

  @JsonProperty("causeStackTrace")
  private String causeStackTrace = null;

  public RestExceptionInfo code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Codi de HTTP de l&#x27;error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.
   * @return code
  **/
  @Schema(required = true, description = "Codi de HTTP de l'error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public RestExceptionInfo errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Missatge de l&#x27;error
   * @return errorMessage
  **/
  @Schema(required = true, description = "Missatge de l'error")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public RestExceptionInfo stackTrace(String stackTrace) {
    this.stackTrace = stackTrace;
    return this;
  }

   /**
   * Stacktrace de l&#x27;excepció si n&#x27;hi hagués.
   * @return stackTrace
  **/
  @Schema(description = "Stacktrace de l'excepció si n'hi hagués.")
  public String getStackTrace() {
    return stackTrace;
  }

  public void setStackTrace(String stackTrace) {
    this.stackTrace = stackTrace;
  }

  public RestExceptionInfo causeException(String causeException) {
    this.causeException = causeException;
    return this;
  }

   /**
   * Tipus de l&#x27;excepció origen (cause) si n&#x27;hi hagués.
   * @return causeException
  **/
  @Schema(description = "Tipus de l'excepció origen (cause) si n'hi hagués.")
  public String getCauseException() {
    return causeException;
  }

  public void setCauseException(String causeException) {
    this.causeException = causeException;
  }

  public RestExceptionInfo causeStackTrace(String causeStackTrace) {
    this.causeStackTrace = causeStackTrace;
    return this;
  }

   /**
   * Stacktrace de l&#x27;excepció origen (cause) si n&#x27;hi hagués.
   * @return causeStackTrace
  **/
  @Schema(description = "Stacktrace de l'excepció origen (cause) si n'hi hagués.")
  public String getCauseStackTrace() {
    return causeStackTrace;
  }

  public void setCauseStackTrace(String causeStackTrace) {
    this.causeStackTrace = causeStackTrace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestExceptionInfo restExceptionInfo = (RestExceptionInfo) o;
    return Objects.equals(this.code, restExceptionInfo.code) &&
        Objects.equals(this.errorMessage, restExceptionInfo.errorMessage) &&
        Objects.equals(this.stackTrace, restExceptionInfo.stackTrace) &&
        Objects.equals(this.causeException, restExceptionInfo.causeException) &&
        Objects.equals(this.causeStackTrace, restExceptionInfo.causeStackTrace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, errorMessage, stackTrace, causeException, causeStackTrace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestExceptionInfo {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    stackTrace: ").append(toIndentedString(stackTrace)).append("\n");
    sb.append("    causeException: ").append(toIndentedString(causeException)).append("\n");
    sb.append("    causeStackTrace: ").append(toIndentedString(causeStackTrace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
