/*
 * API REST INTERNA de Enviafib
 * Conjunt de Serveis REST de Enviafib per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.enviafib@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SigningRequest
 */


public class SigningRequest {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("state")
  private Integer state = null;

  @JsonProperty("rejectionReason")
  private String rejectionReason = null;

  @JsonProperty("additionalInformation")
  private String additionalInformation = null;

  @JsonProperty("custodyURL")
  private String custodyURL = null;

  @JsonProperty("id")
  private Long id = null;

  public SigningRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SigningRequest state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public Integer getState() {
    return state;
  }

  public void setState(Integer state) {
    this.state = state;
  }

  public SigningRequest rejectionReason(String rejectionReason) {
    this.rejectionReason = rejectionReason;
    return this;
  }

   /**
   * Get rejectionReason
   * @return rejectionReason
  **/
  @Schema(description = "")
  public String getRejectionReason() {
    return rejectionReason;
  }

  public void setRejectionReason(String rejectionReason) {
    this.rejectionReason = rejectionReason;
  }

  public SigningRequest additionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Get additionalInformation
   * @return additionalInformation
  **/
  @Schema(description = "")
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  public SigningRequest custodyURL(String custodyURL) {
    this.custodyURL = custodyURL;
    return this;
  }

   /**
   * Get custodyURL
   * @return custodyURL
  **/
  @Schema(description = "")
  public String getCustodyURL() {
    return custodyURL;
  }

  public void setCustodyURL(String custodyURL) {
    this.custodyURL = custodyURL;
  }

  public SigningRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SigningRequest signingRequest = (SigningRequest) o;
    return Objects.equals(this.title, signingRequest.title) &&
        Objects.equals(this.state, signingRequest.state) &&
        Objects.equals(this.rejectionReason, signingRequest.rejectionReason) &&
        Objects.equals(this.additionalInformation, signingRequest.additionalInformation) &&
        Objects.equals(this.custodyURL, signingRequest.custodyURL) &&
        Objects.equals(this.id, signingRequest.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, state, rejectionReason, additionalInformation, custodyURL, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SigningRequest {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    rejectionReason: ").append(toIndentedString(rejectionReason)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    custodyURL: ").append(toIndentedString(custodyURL)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
