/*
 * Dades Obertes de EnviaFIB
 * Conjunt de Serveis REST de EnviaFIB que ofereixen Dades Obertes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.enviafib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.enviafib.apiinterna.client.model.TipusDocumental;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TipusDocumentalsAllElements
 */
@JsonPropertyOrder({
  TipusDocumentalsAllElements.JSON_PROPERTY_NAME,
  TipusDocumentalsAllElements.JSON_PROPERTY_TOTAL_COUNT,
  TipusDocumentalsAllElements.JSON_PROPERTY_DATE_DOWNLOAD,
  TipusDocumentalsAllElements.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TipusDocumentalsAllElements {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TOTAL_COUNT = "total-count";
  private Integer totalCount;

  public static final String JSON_PROPERTY_DATE_DOWNLOAD = "date-download";
  private String dateDownload;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<TipusDocumental> data;

  public TipusDocumentalsAllElements() {
  }

  public TipusDocumentalsAllElements name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Nom descriptiu del que s&#39;està retornant
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public TipusDocumentalsAllElements totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Número total d&#39;elements
   * @return totalCount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalCount() {
    return totalCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  public TipusDocumentalsAllElements dateDownload(String dateDownload) {
    
    this.dateDownload = dateDownload;
    return this;
  }

   /**
   * Data i hora en que s&#39;han retornat les dades. Format ISO-8601
   * @return dateDownload
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATE_DOWNLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDateDownload() {
    return dateDownload;
  }


  @JsonProperty(JSON_PROPERTY_DATE_DOWNLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDateDownload(String dateDownload) {
    this.dateDownload = dateDownload;
  }


  public TipusDocumentalsAllElements data(List<TipusDocumental> data) {
    
    this.data = data;
    return this;
  }

  public TipusDocumentalsAllElements addDataItem(TipusDocumental dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Elements retornats. Pot retornar un null o una llista buida si no hi ha elements.
   * @return data
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TipusDocumental> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(List<TipusDocumental> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TipusDocumentalsAllElements tipusDocumentalsAllElements = (TipusDocumentalsAllElements) o;
    return Objects.equals(this.name, tipusDocumentalsAllElements.name) &&
        Objects.equals(this.totalCount, tipusDocumentalsAllElements.totalCount) &&
        Objects.equals(this.dateDownload, tipusDocumentalsAllElements.dateDownload) &&
        Objects.equals(this.data, tipusDocumentalsAllElements.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, totalCount, dateDownload, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TipusDocumentalsAllElements {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    dateDownload: ").append(toIndentedString(dateDownload)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

