<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>enviafib-ear</artifactId>
    <packaging>ear</packaging>

    <parent>
        <groupId>es.caib.enviafib</groupId>
        <artifactId>enviafib</artifactId>
        <version>2.0.8</version>
    </parent>

    <name>EnviaFIB - Ear</name>

    <properties>
        <!-- Format del timestamp -->
        <maven.build.timestamp.format>dd/MM/yyyy HH:mm</maven.build.timestamp.format>
    </properties>

    <dependencies>
        <!-- Internes -->
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-ejb</artifactId>
            <version>${project.version}</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-back</artifactId>
            <version>${project.version}</version>
            <type>war</type>
        </dependency>

        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-front</artifactId>
            <version>${project.version}</version>
            <type>war</type>
        </dependency>


        <!-- API INTERNA START -->
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-api-interna</artifactId>
            <version>${project.version}</version>
            <type>war</type>
        </dependency>
        <!-- API INTERNA END -->

        <!-- Tenir en compte a l'hora de incloure dependències només si és
        imprescindible 
			i no està ja dins un mòdul sobre el que es pugui establir una dependència 
			als descriptors.
        https://docs.jboss.org/author/display/AS72/Implicit+module+dependencies+for+deployments -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- Externes -->
        <!-- ====================================== -->
        <!-- ===== PLUGINS DE USERINFORMATION ===== -->
        <!-- ====================================== -->

        <dependency>
            <artifactId>pluginsib-userinformation-api</artifactId>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <version>${pluginsib.userinformation.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <artifactId>pluginsib-userinformation-keycloak</artifactId>
            <version>${pluginsib.userinformation.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-multipart-provider</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-jaxrs</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-jaxb-provider</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-jackson2-provider</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <artifactId>pluginsib-userinformation-database</artifactId>
            <version>${pluginsib.userinformation.version}</version>
        </dependency>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <artifactId>pluginsib-userinformation-ldap</artifactId>
            <version>${pluginsib.userinformation.version}</version>
        </dependency>

        <!-- ============================================ -->
        <!-- ========== PLUGINS DE DATAEXPORT =========== -->
        <!-- ============================================ -->
        <!-- API -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.exportdata</groupId>
            <artifactId>pluginsib-exportdata-api</artifactId>
            <version>${pluginsib.exportdata.version}</version>
        </dependency>
        <!-- Excel Plugin -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.exportdata</groupId>
            <artifactId>pluginsib-exportdata-excel</artifactId>
            <version>${pluginsib.exportdata.version}</version>
        </dependency>
        <!-- ODS Plugin -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.exportdata</groupId>
            <artifactId>pluginsib-exportdata-ods</artifactId>
            <version>${pluginsib.exportdata.version}</version>
        </dependency>
        <!-- CSV Plugin -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.exportdata</groupId>
            <artifactId>pluginsib-exportdata-csv</artifactId>
            <version>${pluginsib.exportdata.version}</version>
        </dependency>
        <!-- Commons Dependencies -->
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <!-- <version>2.6</version> -->
        </dependency>
        <dependency>
            <groupId>apache-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.0</version>
        </dependency>


        <!-- ============================================ -->
        <!-- ====    PLUGINS DE ARXIU    === -->
        <!-- ============================================ -->
        
        <dependency>
            <groupId>org.fundaciobit.pluginsib.arxiu</groupId>
            <artifactId>pluginsib-arxiu-api</artifactId>
            <version>${pluginsib.arxiu.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.fundaciobit.pluginsib.arxiu</groupId>
            <artifactId>pluginsib-arxiu-caib</artifactId>
            <version>${pluginsib.arxiu.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>

            </exclusions>
        </dependency>

        <!-- ============================================ -->
        <!-- ==== PLUGINS DE ESTRUCTURA ORGANITZATIVA === -->
        <!-- ============================================ -->

        <dependency>
            <groupId>org.fundaciobit.pluginsib.estructuraorganitzativa</groupId>
            <artifactId>pluginsib-estructuraorganitzativa-api</artifactId>
            <version>${pluginsib.estructuraorganitzativa.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.estructuraorganitzativa</groupId>
            <artifactId>pluginsib-estructuraorganitzativa-mock</artifactId>
            <version>${pluginsib.estructuraorganitzativa.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.estructuraorganitzativa</groupId>
            <artifactId>pluginsib-estructuraorganitzativa-database</artifactId>
            <version>${pluginsib.estructuraorganitzativa.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.estructuraorganitzativa</groupId>
            <artifactId>pluginsib-estructuraorganitzativa-ldapcaib</artifactId>
            <version>${pluginsib.estructuraorganitzativa.version}</version>
        </dependency>

    </dependencies>


    <build>
        <finalName>enviafib</finalName>

        <filters>
            <filter>../config.properties</filter>
        </filters>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-ear-plugin</artifactId>

                    <!-- configuring the ear plugin -->
                    <configuration>

                        <displayName>EnviaFIB</displayName>
                        <description>EnviaFIB</description>

                        <generateApplicationXml>true</generateApplicationXml>
                        <defaultLibBundleDir>lib</defaultLibBundleDir>
                        <includeLibInApplicationXml>false</includeLibInApplicationXml>
                        <!--suppress UnresolvedMavenProperty -->
                        <!-- Nom mòduls d'acord amb punt 4.2 de l'Estàndard CAIB -->
                        <outputFileNameMapping>
                            @{artifactId}@-@{version}@.@{extension}@</outputFileNameMapping>

                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            </manifest>
                            <manifestEntries>
                                <project-version>${project.version}</project-version>
                                <project-buildtime>${maven.build.timestamp}</project-buildtime>
                                <scm-revision>${buildNumber}</scm-revision>
                            </manifestEntries>
                        </archive>

                        <defaultLibBundleDir>lib</defaultLibBundleDir>
                        <skinnyWars>true</skinnyWars>

                        <packagingExcludes>
                                
                                
                            <!-- Requereix afegir mòdul 'com.fasterxml.jackson.core.jackson-core' a jboss-deployment-structure.xml -->
                             **/jackson-core*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.codehaus.jackson.jackson-jaxrs' a jboss-deployment-structure.xml -->
                             **/jackson-jaxrs*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider' a jboss-deployment-structure.xml -->
                             **/jackson-jaxrs-json-provider*redhat*.jar,
                             **/jackson-jaxrs-base*redhat*.jar,
                             **/jackson-module-jaxb-annotations*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.codehaus.jackson.jackson-xc' a jboss-deployment-structure.xml -->
                             **/jackson-xc*redhat*.jar,
                            <!-- Requereix afegir mòdul 'javax.ws.rs.api' a jboss-deployment-structure.xml -->
                             **/jboss-jaxrs-api_2.1_spec*redhat*.jar,
                             **/jsr311-api-1.1.1.jar,
                            <!-- Requereix afegir mòdul 'org.jboss.resteasy.resteasy-jackson2-provider' a jboss-deployment-structure.xml -->
                             **/resteasy-jackson2-provider*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.apache.commons.codec' a jboss-deployment-structure.xml -->
                             **/commons-codec*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.sun.istack' a jboss-deployment-structure.xml -->
                             **/istack-commons-runtime*redhat*.jar,
                             **/istack-commons-tools*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.apache.commons.io' a jboss-deployment-structure.xml -->
                             **/commons-io*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.google.guava' a jboss-deployment-structure.xml -->
                             **/guava*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.apache.james.mime4j' a jboss-deployment-structure.xml -->
                             **/apache-mime4j*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.google.code.gson' a jboss-deployment-structure.xml -->
                             **/gson*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.fasterxml.jackson.core.jackson-databind' a jboss-deployment-structure.xml -->
                             **/jackson-databind*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.apache.httpcomponents.core' a jboss-deployment-structure.xml -->
                             **/httpclient*redhat*.jar,
                             **/httpcore*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.github.fge.jackson-coreutils' a jboss-deployment-structure.xml -->
                             **/jackson-coreutils*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.fasterxml.jackson.datatype.jackson-datatype-jsr310' a jboss-deployment-structure.xml -->
                             **/jackson-datatype-jsr310*redhat*.jar,
                            <!-- Requereix afegir mòdul 'javax.json.bind.api' a jboss-deployment-structure.xml -->
                             **/javax.json.bind-api*redhat*.jar,
                            <!-- Requereix afegir mòdul 'javax.annotation.api' a jboss-deployment-structure.xml -->
                             **/jboss-annotations-api_1.3_spec*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.reactivestreams' a jboss-deployment-structure.xml -->
                             **/reactive-streams*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.jboss.resteasy.resteasy-multipart-provider' a jboss-deployment-structure.xml -->
                             **/resteasy-multipart-provider*redhat*.jar,
                            <!-- Requereix afegir mòdul 'javax.validation.api' a jboss-deployment-structure.xml -->
                             **/validation-api*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.bouncycastle' a jboss-deployment-structure.xml -->
                             **/bcprov-jdk15on*redhat*.jar,
                             **/bcmail-jdk15on*redhat*.jar,
                             **/bcpkix-jdk15on*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.jboss.ejb3' a jboss-deployment-structure.xml -->
                             **/jboss-ejb3-ext-api*redhat*.jar,

                            <!-- Requereix afegir mòdul 'net.jcip' a jboss-deployment-structure.xml -->
                             **/jcip-annotations*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.jboss.resteasy.resteasy-jaxrs' a jboss-deployment-structure.xml -->
                             **/resteasy-jaxrs*redhat*.jar,
                             **/resteasy-client*redhat*.jar,
                             **/resteasy-client-microprofile*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.fasterxml.jackson.core.jackson-annotations' a jboss-deployment-structure.xml -->
                             **/jackson-annotations*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.codehaus.jackson.jackson-core-asl' a jboss-deployment-structure.xml -->
                             **/jackson-core-asl*redhat*.jar,

                             <!-- Requereix afegir mòdul 'javax.xml.bind.api' a jboss-deployment-structure.xml -->
                             **/jboss-jaxb-api_2.3_spec*redhat*.jar,
                             **/jaxb-api-2.3.1.jar,                             
                            <!-- Requereix afegir mòdul 'com.sun.xml.bind' a jboss-deployment-structure.xml -->
                             **/jaxb-runtime*redhat*.jar,
                             **/jaxb-xjc*redhat*.jar,
                             **/jaxb-jxc*redhat*.jar,
                             **/codemodel*redhat*.jar,
                             **/rngom*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.codehaus.jettison' a jboss-deployment-structure.xml -->
                             **/jettison*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.sun.xml.fastinfoset' a jboss-deployment-structure.xml -->
                             **/FastInfoset*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.codehaus.jackson.jackson-mapper-asl' a jboss-deployment-structure.xml -->
                             **/jackson-mapper-asl*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.github.fge.json-patch' a jboss-deployment-structure.xml -->
                             **/json-patch*redhat*.jar,
                            <!-- Requereix afegir mòdul 'org.jboss.resteasy.resteasy-jaxb-provider' a jboss-deployment-structure.xml -->
                             **/resteasy-jaxb-provider*redhat*.jar,
                            <!-- Requereix afegir mòdul 'com.sun.xml.txw2' a jboss-deployment-structure.xml -->
                             **/txw2*redhat*.jar,
    
                            <!-- Requereix afegir mòdul 'javax.activation.api' a jboss-deployment-structure.xml -->
                            **/activation*redhat*.jar,

                            **/javax.mail*redhat*.jar,

                            **/commons-logging-jboss-logging*redhat*.jar,

                            <!-- Requereix afegir mòdul 'org.slf4j' a jboss-deployment-structure.xml -->
                            **/slf4j-api*redhat*.jar,

                        </packagingExcludes>

                        <modules>

                            <webModule>
                                <groupId>es.caib.enviafib</groupId>
                                <artifactId>enviafib-back</artifactId>
                                <contextRoot>enviafibback</contextRoot>
                                <bundleFileName>enviafib-back.war</bundleFileName>
                            </webModule>

                            <webModule>
                                <groupId>es.caib.enviafib</groupId>
                                <artifactId>enviafib-front</artifactId>
                                <contextRoot>enviafibfront</contextRoot>
                                <bundleFileName>enviafib-front.war</bundleFileName>
                            </webModule>

                            <ejbModule>
                                <groupId>es.caib.enviafib</groupId>
                                <artifactId>enviafib-ejb</artifactId>
                                <bundleFileName>enviafib-ejb.jar</bundleFileName>
                            </ejbModule>

                            <!-- API INTERNA START -->
                            <webModule>
                                <groupId>es.caib.enviafib</groupId>
                                <artifactId>enviafib-api-interna</artifactId>
                                <contextRoot>/enviafibapi/interna</contextRoot>
                                <bundleFileName>enviafib-api-interna.war</bundleFileName>
                            </webModule>
                            <!-- API INTERNA END -->

                        </modules>

                        <!--
                        <packagingExcludes>lib/jackson-*.jar,lib/resteasy-*.jar</packagingExcludes> -->

                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>


    <profiles>
        <!-- Garantir que es fixa la variable d'entorn JBOSS_HOME -->
        <profile>
            <id>fix JBOSS_HOME</id>
            <activation>
                <property>
                    <name>!env.JBOSS_HOME</name>
                </property>
            </activation>
            <properties>
                <env.JBOSS_HOME>HA DE FIXAR LA VARIABLE D'ENTORN JBOSS_HOME</env.JBOSS_HOME>
            </properties>
        </profile>
        <profile>
            <id>revisionnumber</id>
            <build>
                <plugins>
                    <!-- Defineix la propietat ${buildNumber} que s'empra al
                    filtrat -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>buildnumber-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
