<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>enviafib</artifactId>
        <groupId>es.caib.enviafib</groupId>
        <version>2.0.9</version>
    </parent>
    <artifactId>enviafib-api-interna</artifactId>
    <packaging>war</packaging>
    <name>EnviaFIB - API Rest - Interna Server</name>
    <properties>
        <auth.method>BASIC</auth.method>
        <client.default.package>es.caib.enviafib.apiinterna.client</client.default.package>
    </properties>
    <dependencies>
        <!-- Especificacions i llibreries proporcionades per JBoss -->
        <dependency>
            <groupId>org.jboss.spec</groupId>
            <artifactId>jboss-javaee-8.0</artifactId>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Altres mòduls del projecte -->
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-commons</artifactId>
            <version>2.0.9</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-persistence</artifactId>
            <version>2.0.9</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.activation</groupId>
                    <artifactId>javax.activation-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <artifactId>portafib-callback-beans</artifactId>
            <groupId>es.caib.portafib</groupId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>es.caib.enviafib</groupId>
            <artifactId>enviafib-ejb</artifactId>
            <version>2.0.9</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
        </dependency>
        <!-- Anotacions de documentació de openapi -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.1.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <artifactId>pluginsib-utils-rest</artifactId>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <version>${pluginsib.utils.version}</version>
        </dependency>
        
        <!-- Swagger UI Configurable-->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-swagger-ui-configurable-webjar</artifactId>
            <version>${pluginsib.utils.version}</version>
        </dependency>
       
    </dependencies>
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <!-- Genera el descriptor openapi.json de forma estàtica, després 
                el posarem l'arrel del WAR -->
            <!-- https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-maven-plugin -->
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>2.2.15</version>
                <configuration>
                    <outputFormat>JSON</outputFormat>
                    <prettyPrint>TRUE</prettyPrint>
                    <outputPath>${project.basedir}/openapi/</outputPath>                   
                </configuration>
                <executions>
                    <execution>
                        <id>openapi1</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                        <configuration>
                            <contextId>Dades Obertes</contextId>
                            <outputFileName>openapi_dadesobertes</outputFileName>
                            <resourcePackages>
                                <package>es.caib.enviafib.api.interna.config</package>
                                <package>es.caib.enviafib.api.interna.secure.dadesobertes</package>
                            </resourcePackages>
                        </configuration>
                    </execution>
                    <execution>
                        <id>openapi2</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                        <configuration>
                            <contextId>PortaFIB Callback</contextId>
                            <outputFileName>openapi_portafibcallback</outputFileName>
                            <resourcePackages>
                                <package>es.caib.enviafib.api.interna.config</package>
                                <package>es.caib.enviafib.api.interna.all.portafibcallback</package>
                            </resourcePackages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <!--  NOTA: No generam client ja que la primera API és el CallBack de PortaFIB -->
            <!--  i l'altra API és DadesObertes (Que no necessita client java ja que accedeixen directament) -->


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includeProjectDependencies>false</includeProjectDependencies>
                    <includePluginDependencies>true</includePluginDependencies>
                    <executableDependency>
                        <artifactId>pluginsib-utils-rest</artifactId>
                        <groupId>org.fundaciobit.pluginsib.utils</groupId>
                    </executableDependency>
                    <mainClass>
                        org.fundaciobit.pluginsib.utils.rest.pomadaptertojboss72.AdaptApiClientPomToJboss72</mainClass>
                    <arguments>
                        <argument>${project.basedir}</argument>
                    </arguments>

                </configuration>
                <dependencies>
                    <dependency>
                        <artifactId>pluginsib-utils-rest</artifactId>
                        <groupId>org.fundaciobit.pluginsib.utils</groupId>
                        <version>${pluginsib.utils.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <!-- Inclou el openapi.json i el swagger-ui dins el war -->
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
                    
                    <packagingExcludes>**/commons-lang3*redhat*.jar</packagingExcludes>
                    
                    
                    <webResources>
                        <resource>
                            <directory>${project.basedir}/openapi</directory>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
            
        </plugins>
        
    </build>
</project>