/*
 * API REST INTERNA de Enviafib
 * Conjunt de Serveis REST de Enviafib per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.enviafib@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.enviafib.apiinterna.client.services.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
